### ISSUE TITLE
[BUG] Blocks push in random directions

### ISSUE THREAD

**Issue by CJGithub310** [Rebirth-of-the-Night/Rebirth-Of-The-Night#602]
**Describe the bug**
When standing or walking on blocks like Leaves (Dynamic leaves specifically), Mud, and Ash Blocks, it pushes you around in random directions, and sometimes doesn't allow you to walk forward, as if there's an invisible barrier in front of you. I assume this has something to do with the fact that you sink into these blocks, and that the edges of the blocks may produce some kind of strange barrier-like glitch, and the reason I may be being pushed around is because the game may think of this block as both entirely solid and not quite solid at the same time, therefore it reproduces the same behavior that would happen if you used the command "/setblock minecraft:___ ~ ~ ~": it would push you away from it into an air block you can walk in.

**To Reproduce**
Just step on the blocks, you'll see what's wrong

**Expected behavior**
You should just be able to walk in these blocks like normal, with Leaves slightly slowing you down, along with Mud and Ash Blocks, as would happen in the older versions.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 Beta 3
 - Server or Singleplayer: Singleplayer, though it may also be the same on servers
 - Version the world was created on: 3.0 Beta 3

**Additional context**

**Comment by Fate1098** [comment]
This issue also occurs on my Akliz server. Flesh blocks in the nether also seem to have this issue.

Modpack Version: 3.0 Beta 3
Server or Singleplayer: Akliz Server
Version the world was created on: 3.0 Beta 3

**Comment by TheNelston** [comment]
Must be a new addition in Beta 3, not replicable on Beta 2

**Comment by CJGithub310** [comment]
This issue IS NEW to 3.0 Beta 3. I don't know what caused it, but I hope it is fixed soon since it makes travelling through Ashen Inferno biomes incredibly challenging.

**Comment by kaporli** [comment]
If anyone hasn't figured it out yet, the mod Fragile Glass and Thin Ice is causing this issue. I had the same problem until I removed the mod from my list.

**Comment by democat3457** [comment]
hmmmmmmm

**Comment by Foreck1** [comment]
That's interesting, it wasn't the case several commits ago, so there must be something that broke, we'll look into it

**Comment by Foreck1** [comment]
I tried uninstalling Fragile Glass but the bug persists, so it's not that in our case.

**Comment by kaporli** [comment]
That's really odd... it fixed the issue for me, sorry.

**Comment by bradleyq** [comment]
This issue looks to be caused by the updated version of Aqua Acrobatics. For any who need a workaround right away, go into the mod configuration and set "Push Player Out Of Blocks" to APPROXIMATE or STANDARD. This worked for me.
